_format_version: "3.0"
services:
- host: bookings.kongair
  id: e51d368f-0d2e-5877-8854-ce49d173f9b8
  name: bookings-service-finastra
  path: /
  plugins:
  - _config: default-jwt
    enabled: true
    name: jwt
  port: 8082
  protocol: http
  routes:
  - id: b8f47ae3-172b-554f-8cd7-ca25fb96219b
    methods:
    - GET
    name: bookings-service-finastra_get-bookings
    paths:
    - ~/bookings$
    plugins: []
    regex_priority: 200
    strip_path: false
    tags:
    - sales
  - id: 84fa5fd3-6bbc-5f8c-9478-037654682239
    methods:
    - POST
    name: bookings-service-finastra_post-booking
    paths:
    - ~/bookings$
    plugins: []
    regex_priority: 200
    strip_path: false
    tags:
    - sales
  - id: 8c793911-a9fc-5b3e-b3b0-3fcc98c8cd40
    methods:
    - GET
    name: bookings-service-finastra_get-health
    paths:
    - ~/health$
    plugins: []
    regex_priority: 200
    strip_path: false
    tags:
    - sales
  tags:
  - sales
upstreams: []
