name: Deploy Kong changes to PRD

on:
  push:
    branches:
      - main
    paths:
      - PRD/kong/kong.yaml
      - .github/workflows/deploy-kong-PRD.yaml
  workflow_dispatch:

jobs:

#  this job is useful to debug workflows, see https://github.com/mheap/debug-artifact
#  debug-artifacts:
#    name: Upload Debug Artifacts
#    runs-on: ubuntu-latest
#    steps:
#      - name: Upload Debug Artifacts
#        uses: mheap/debug-artifact@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-kong:
    name: Deploy Kong to PRD
    runs-on: ubuntu-latest
    environment: prd

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup deck
        uses: kong/setup-deck@v1
        with:
          deck-version: '1.58.0'
          wrapper: false

      - name: deck sync konnect
        if: vars.DEPLOY_TARGET == 'KONNECT' || vars.DEPLOY_TARGET == ''
        run: |
           deck gateway sync --select-tag platform-repo-managed \
               --konnect-control-plane-name "${{ vars.KONNECT_CP_NAME }}" \
               --konnect-token ${{ secrets.KONNECT_PAT }} \
               --konnect-addr "${{ vars.KONNECT_ADDR }}" \
               PRD/kong/kong.yaml
