name: Stage changes for Kong

on:
  push:
    branches:
      - main
      - workflow/**
      - contract-test
    paths-ignore:
      - 'PRD/**'
      - 'platform/kong/.generated/kong.yaml'
  workflow_dispatch:

jobs:

  has-changes:
    name: Have specs, configurations, or pipeline files changed
    runs-on: ubuntu-latest

    outputs:
      are-changes: ${{ steps.changed-files.outputs.files }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changed-files
        with:
          filters: |
            files:
              - '.github/workflows/stage-changes-for-kong.yaml'
              - 'flight-data/flights/openapi.yaml'
              - 'flight-data/flights/kong/**'
              - 'flight-data/routes/openapi.yaml'
              - 'flight-data/routes/kong/**'
              - 'sales/bookings/opeanapi.yaml'
              - 'sales/bookings/kong/**'
              - 'sales/customer/opeanapi.yaml'
              - 'sales/customer/kong/**'
              - 'experience/kong/**'
              - 'platform/kong/**'

  oas-break:
    name: Check breaking changes
    needs: has-changes
    if: ${{ needs.has-changes.outputs.are-changes == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - dir: flight-data
            name: flights
            port: 8080
          - dir: flight-data
            name: routes
            port: 8081
          - dir: sales
            name: bookings
            port: 8082
          - dir: sales
            name: customer
            port: 8083

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Base OAS
        run: |
          git show HEAD~1:${{ matrix.app.dir }}/${{ matrix.app.name }}/openapi.yaml > ${{ matrix.app.dir }}/${{ matrix.app.name }}/base.yaml
          echo "Base OAS path: ${{ matrix.app.dir }}/${{ matrix.app.name }}/base.yaml"
          cat ${{ matrix.app.dir }}/${{ matrix.app.name }}/base.yaml
      - name: Check OAS breaking changes
        uses: oasdiff/oasdiff-action/breaking@main
        id: oasdiff
        with:
          base: ${{ matrix.app.dir }}/${{ matrix.app.name }}/base.yaml
          revision: ${{ matrix.app.dir }}/${{ matrix.app.name }}/openapi.yaml
      - name: Create Issue on Breaking Change
        if: steps.oasdiff.outputs.breaking != 'No breaking changes'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_NAME: ${{ matrix.app.name }}
          BREAKING_CHANGES: ${{ steps.oasdiff.outputs.breaking }}
        with:
          filename: .github/ISSUE_TEMPLATE/breaking-change.md

  oas-to-kong:
    name: Convert OAS to Kong configurations
    needs: [has-changes, oas-break]
    if: ${{ needs.has-changes.outputs.are-changes == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup deck
        uses: kong/setup-deck@v1
        with:
          deck-version: '1.58.0'
          wrapper: false

      - name: Convert Flights API to Kong
        run: |
          deck file openapi2kong -s flight-data/flights/openapi.yaml | \
            deck file patch flight-data/flights/kong/patches.yaml | \
            deck file add-tags -o .github/artifacts/kong/flight-data-flights-kong.yaml \
              --selector "$.services[*]" --selector "$.services[*].routes[*]" flight-data1

      - name: Convert Routes API to Kong
        run: |
          deck file openapi2kong -s flight-data/routes/openapi.yaml | \
            deck file patch flight-data/routes/kong/patches.yaml | \
            deck file add-tags -o .github/artifacts/kong/flight-data-routes-kong.yaml \
              --selector "$.services[*]" --selector "$.services[*].routes[*]" route-data

      - name: Convert Bookings API to Kong
        run: |
          deck file openapi2kong -s sales/bookings/openapi.yaml | \
            deck file patch  sales/bookings/kong/patches.yaml | \
            deck file add-tags -o .github/artifacts/kong/sales-bookings-kong.yaml \
              --selector "$.services[*]" --selector "$.services[*].routes[*]" sales

      - name: Convert Customers API to Kong
        run: |
          deck file openapi2kong -s sales/customer/openapi.yaml | \
            deck file patch sales/customer/kong/patches.yaml | \
            deck file add-tags -o .github/artifacts/kong/sales-customer-kong.yaml --selector "$.services[*]" \
              --selector "$.services[*].routes[*]" sales

      - name: Combine Kong Configurations
        run: |
          deck file merge \
            .github/artifacts/kong/*-kong.yaml -o .github/artifacts/kong/kong-combined.yaml

      - name: Merge Experience API Configurations
        run: |
          deck file merge \
            .github/artifacts/kong/kong-combined.yaml experience/kong/experience-service.yaml \
            -o .github/artifacts/kong/kong-combined.yaml

      - name: Platform Team Kong Additions
        run: |
          deck file merge \
            .github/artifacts/kong/kong-combined.yaml \
            platform/kong/platform-kong-base.yaml     \
            platform/kong/consumers/*                 \
            platform/kong/plugins/*                   \
            platform/kong/vaults/* |                  \
          deck file patch \
            platform/kong/patches.yaml |
          deck file add-tags \
            -o platform/kong/.generated/kong.yaml \
            "platform-repo-managed"

      - name: Kong linting
        run: deck file lint -s platform/kong/.generated/kong.yaml platform/kong/lint-rulesets.yaml

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kong-configurations
          path: .github/artifacts/kong/*.yaml

      - name: Create PR for changed Kong Gateway Configuration
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          title: Stage Kong Gateway Configuration

